version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: crm-mongodb
    ports:
      - "27016:27017"  # Changed to use port 27016 on host
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
  backend:
    build: .
    image: php:cli
    container_name: phpbackend
    ports:
      - "8001:8001"
    volumes: 
      - ./backend:/backend
    working_dir: /backend
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://admin:password@mongodb:27017/crm?authSource=admin
      - JWT_SECRET=58d9a29b3548a77d12f85b81f38d07f0282cb4c092d1cc30052069820229c550
      - JWT_EXPIRATION=3600
    command: php -S 0.0.0.0:8001
volumes:
  mongodb_data: