name: SonarQube Scan

on:
  push:
    branches:
      - main

jobs:
  sonar:
    runs-on: ubuntu-latest  # Change to 'windows-latest' if needed

    services:
      sonarqube:
        image: sonarqube:lts
        ports:
          - 9000:9000
        env:
          SONARQUBE_JDBC_URL: jdbc:h2:mem:sonarqube

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Wait for SonarQube to Start
        run: |
          echo "Waiting for SonarQube..."
          for i in {1..30}; do
            if curl -s http://localhost:9000/api/system/status | grep -q "UP"; then
              echo "SonarQube is ready!"
              exit 0
            fi
            sleep 5
          done
          echo "SonarQube did not start in time"
          exit 1

      - name: SonarQube Scan
        run: sonar-scanner
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
